package com.pengjinfei.mybatis.mapper;

import com.pengjinfei.mybatis.domain.BatchJobExecution;
import java.math.BigDecimal;

public interface BatchJobExecutionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCH_JOB_EXECUTION
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal jobExecutionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCH_JOB_EXECUTION
     *
     * @mbggenerated
     */
    int insert(BatchJobExecution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCH_JOB_EXECUTION
     *
     * @mbggenerated
     */
    int insertSelective(BatchJobExecution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCH_JOB_EXECUTION
     *
     * @mbggenerated
     */
    BatchJobExecution selectByPrimaryKey(BigDecimal jobExecutionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCH_JOB_EXECUTION
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BatchJobExecution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCH_JOB_EXECUTION
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BatchJobExecution record);
}