package com.pengjinfei.mybatis.mapper;

import com.pengjinfei.mybatis.config.BaseMapper;
import com.pengjinfei.mybatis.domain.BatchJobExecutionParams;
import com.pengjinfei.mybatis.domain.BatchJobExecutionParamsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BatchJobExecutionParamsMapper extends BaseMapper<BatchJobExecutionParams> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCH_JOB_EXECUTION_PARAMS
     *
     * @mbggenerated
     */
    int countByExample(BatchJobExecutionParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCH_JOB_EXECUTION_PARAMS
     *
     * @mbggenerated
     */
    int insert(BatchJobExecutionParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCH_JOB_EXECUTION_PARAMS
     *
     * @mbggenerated
     */
    int insertSelective(BatchJobExecutionParams record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCH_JOB_EXECUTION_PARAMS
     *
     * @mbggenerated
     */
    List<BatchJobExecutionParams> selectByExample(BatchJobExecutionParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCH_JOB_EXECUTION_PARAMS
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BatchJobExecutionParams record, @Param("example") BatchJobExecutionParamsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BATCH_JOB_EXECUTION_PARAMS
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BatchJobExecutionParams record, @Param("example") BatchJobExecutionParamsExample example);
}