package com.pengjinfei.mybatis.domain;

import java.math.BigDecimal;
import java.util.Date;

public class BatchJobExecutionParams {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION_PARAMS.JOB_EXECUTION_ID
     *
     * @mbggenerated
     */
    private BigDecimal jobExecutionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION_PARAMS.TYPE_CD
     *
     * @mbggenerated
     */
    private String typeCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION_PARAMS.KEY_NAME
     *
     * @mbggenerated
     */
    private String keyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION_PARAMS.STRING_VAL
     *
     * @mbggenerated
     */
    private String stringVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION_PARAMS.DATE_VAL
     *
     * @mbggenerated
     */
    private Date dateVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION_PARAMS.LONG_VAL
     *
     * @mbggenerated
     */
    private BigDecimal longVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION_PARAMS.DOUBLE_VAL
     *
     * @mbggenerated
     */
    private Short doubleVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION_PARAMS.IDENTIFYING
     *
     * @mbggenerated
     */
    private String identifying;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION_PARAMS.JOB_EXECUTION_ID
     *
     * @return the value of BATCH_JOB_EXECUTION_PARAMS.JOB_EXECUTION_ID
     *
     * @mbggenerated
     */
    public BigDecimal getJobExecutionId() {
        return jobExecutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION_PARAMS.JOB_EXECUTION_ID
     *
     * @param jobExecutionId the value for BATCH_JOB_EXECUTION_PARAMS.JOB_EXECUTION_ID
     *
     * @mbggenerated
     */
    public void setJobExecutionId(BigDecimal jobExecutionId) {
        this.jobExecutionId = jobExecutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION_PARAMS.TYPE_CD
     *
     * @return the value of BATCH_JOB_EXECUTION_PARAMS.TYPE_CD
     *
     * @mbggenerated
     */
    public String getTypeCd() {
        return typeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION_PARAMS.TYPE_CD
     *
     * @param typeCd the value for BATCH_JOB_EXECUTION_PARAMS.TYPE_CD
     *
     * @mbggenerated
     */
    public void setTypeCd(String typeCd) {
        this.typeCd = typeCd == null ? null : typeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION_PARAMS.KEY_NAME
     *
     * @return the value of BATCH_JOB_EXECUTION_PARAMS.KEY_NAME
     *
     * @mbggenerated
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION_PARAMS.KEY_NAME
     *
     * @param keyName the value for BATCH_JOB_EXECUTION_PARAMS.KEY_NAME
     *
     * @mbggenerated
     */
    public void setKeyName(String keyName) {
        this.keyName = keyName == null ? null : keyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION_PARAMS.STRING_VAL
     *
     * @return the value of BATCH_JOB_EXECUTION_PARAMS.STRING_VAL
     *
     * @mbggenerated
     */
    public String getStringVal() {
        return stringVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION_PARAMS.STRING_VAL
     *
     * @param stringVal the value for BATCH_JOB_EXECUTION_PARAMS.STRING_VAL
     *
     * @mbggenerated
     */
    public void setStringVal(String stringVal) {
        this.stringVal = stringVal == null ? null : stringVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION_PARAMS.DATE_VAL
     *
     * @return the value of BATCH_JOB_EXECUTION_PARAMS.DATE_VAL
     *
     * @mbggenerated
     */
    public Date getDateVal() {
        return dateVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION_PARAMS.DATE_VAL
     *
     * @param dateVal the value for BATCH_JOB_EXECUTION_PARAMS.DATE_VAL
     *
     * @mbggenerated
     */
    public void setDateVal(Date dateVal) {
        this.dateVal = dateVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION_PARAMS.LONG_VAL
     *
     * @return the value of BATCH_JOB_EXECUTION_PARAMS.LONG_VAL
     *
     * @mbggenerated
     */
    public BigDecimal getLongVal() {
        return longVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION_PARAMS.LONG_VAL
     *
     * @param longVal the value for BATCH_JOB_EXECUTION_PARAMS.LONG_VAL
     *
     * @mbggenerated
     */
    public void setLongVal(BigDecimal longVal) {
        this.longVal = longVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION_PARAMS.DOUBLE_VAL
     *
     * @return the value of BATCH_JOB_EXECUTION_PARAMS.DOUBLE_VAL
     *
     * @mbggenerated
     */
    public Short getDoubleVal() {
        return doubleVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION_PARAMS.DOUBLE_VAL
     *
     * @param doubleVal the value for BATCH_JOB_EXECUTION_PARAMS.DOUBLE_VAL
     *
     * @mbggenerated
     */
    public void setDoubleVal(Short doubleVal) {
        this.doubleVal = doubleVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION_PARAMS.IDENTIFYING
     *
     * @return the value of BATCH_JOB_EXECUTION_PARAMS.IDENTIFYING
     *
     * @mbggenerated
     */
    public String getIdentifying() {
        return identifying;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION_PARAMS.IDENTIFYING
     *
     * @param identifying the value for BATCH_JOB_EXECUTION_PARAMS.IDENTIFYING
     *
     * @mbggenerated
     */
    public void setIdentifying(String identifying) {
        this.identifying = identifying == null ? null : identifying.trim();
    }
}