spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url:  jdbc\:oracle\:thin\:@//192.168.99.100\:49161/XE
    username: pengjinfei
    password: oracle
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
