/*
INSERT INTO PERSON (ID,NAME,AGE,ADDRESS ) VALUES (1,'AA',21,'北京');
INSERT INTO PERSON (ID,NAME,AGE,ADDRESS ) VALUES (2,'BB',34,'南京');
INSERT INTO PERSON (ID,NAME,AGE,ADDRESS ) VALUES (3,'CC',65,'天津');
INSERT INTO PERSON (ID,NAME,AGE,ADDRESS ) VALUES (4,'DD',23,'武、汉');
INSERT INTO PERSON (ID,NAME,AGE,ADDRESS ) VALUES (5,'EE',67,'深圳');
INSERT INTO PERSON (ID,NAME,AGE,ADDRESS ) VALUES (6,'FF',256,'广州');
INSERT INTO PERSON (ID,NAME,AGE,ADDRESS ) VALUES (7,'GG',23,'台山');
INSERT INTO PERSON (ID,NAME,AGE,ADDRESS ) VALUES (8,'HH',24,'山东');
INSERT INTO PERSON (ID,NAME,AGE,ADDRESS ) VALUES (9,'II',22,'西安');
INSERT INTO PERSON (ID,NAME,AGE,ADDRESS ) VALUES (10,'JJ',24,'三亚');

*/
